# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Idpbuilder < Formula
  desc ""
  homepage "https://cnoe.io"
  version "0.4.5"
  depends_on :linux

  on_intel do
    if Hardware::CPU.is_64_bit?
      url "https://github.com/nimakaviani/idpbuilder/releases/download/v0.4.5/idpbuilder-linux-amd64.tar.gz"
      sha256 "2901581fafc04d873bbd784f4eab9a711931b225ef7625e8a68c22ea65b86b87"

      def install
        bin.install "idpbuilder"
      end
    end
  end

  test do
    system "#{bin}/idpbuilder --version"
  end
end
